name: Test python files

on:
    pull_request:
        branch:
            - main
jobs:
    run_tests:
        runs-on: ubuntu-latest

    steps:
        - name: checkout repo
        uses: actions/Checkout@v3

        - name: install python
        uses: action/setup-python

        - name: install requirements
        run: pip install -r requirements.txt

        - name: run tests
        run: pytest